[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_staking = "5xegvvEypwkoYsvcRN3TcMyVg66ENihYMZu19obgc6t1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/vipin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
